#---
# tasks file for mysql

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - mysql-server
    - python-mysqldb

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present
  become: yes

- name: Create local mysql user
  mysql_user: 
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}  
    priv=*.*:ALL
  become: yes

- name: Create remoute mysql user
  mysql_user:
    name={{ wp_remoute_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL
  become: yes  

- name: allow remoute connection
  become: yes
  lineinfile:
   dest=/etc/mysql/mysql.conf.d/mysqld.cnf
   regexp="(.)+bind-address"
   line="bind-adress = {{ wp_web_host }}"
